/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './templates/**/*.html',
    './App.tsx',
    './index.tsx',
    './{components,pages,contexts,services,hooks,utils}/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#8B7BD8',
        'primary-dark': '#6B5BB8',
        'primary-light': '#A78BFA',
        'background-deep': '#0F172A',
        background: '#1E293B',
        surface: 'rgba(255, 255, 255, 0.05)',
        'surface-hover': 'rgba(255, 255, 255, 0.08)',
        'text-primary': '#F8FAFC',
        'text-secondary': '#CBD5E1',
        'text-tertiary': '#94A3B8',
        'text-muted': '#64748B',
        'text-disabled': '#475569',
        'accent-coral': '#FF6B6B',
        'accent-sage': '#84A98C',
        'accent-green': '#10B981',
        'accent-red': '#EF4444',
        'border-light': 'rgba(255, 255, 255, 0.1)',
        'border-medium': 'rgba(255, 255, 255, 0.15)',
        'border-primary': 'rgba(139, 123, 216, 0.3)',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          "'Segoe UI'",
          'Roboto',
          'Oxygen',
          'Ubuntu',
          'Cantarell',
          'sans-serif',
        ],
        mono: ['Monaco', "'Courier New'", 'monospace'],
      },
      fontSize: {
        xs: '11px',
        sm: '13px',
        base: '14px',
        md: '15px',
        lg: '16px',
        xl: '18px',
        '2xl': '20px',
        '3xl': '24px',
        '4xl': '32px',
        '5xl': '42px',
        'story-heading': 'var(--font-heading, 48px)',
        'story-subtitle': 'var(--font-subtitle, 26px)',
        'story-date': 'var(--font-date, 16px)',
        'story-class': 'var(--font-class, 22px)',
        'story-time': 'var(--font-time, 20px)',
        'story-instructor': 'var(--font-instructor, 18px)',
        'story-location': 'var(--font-location, 16px)',
        'story-description': 'var(--font-description, 16px)',
        'story-footer': 'var(--font-footer, 18px)',
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '10px',
        xl: '12px',
        '2xl': '16px',
        '3xl': '20px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 2px 4px rgba(0, 0, 0, 0.2)',
        md: '0 4px 12px rgba(0, 0, 0, 0.2)',
        lg: '0 8px 24px rgba(0, 0, 0, 0.3)',
        xl: '0 20px 60px rgba(0, 0, 0, 0.3)',
        primary: '0 4px 16px rgba(139, 123, 216, 0.3)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
      },
      keyframes: {
        'slow-pulse': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.1)', opacity: '0.8' },
        },
        'slide-up-fade': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      animation: {
        'pulse-a': 'slow-pulse 9s ease-in-out infinite',
        'pulse-b': 'slow-pulse 11s ease-in-out infinite',
        'fade-slide': 'slide-up-fade 0.6s ease forwards',
        'fade-in': 'fade-in 0.3s ease forwards',
        float: 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
